name: Python CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v3

      - name: Installer Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Installer les dépendances
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt || true

      - name: Vérifier la qualité du code avec Flake8
        uses: py-actions/flake8@v2
        with:
          path: "."          
          exclude: "venv ,.git"

      - name: Exécuter les tests
        run: |
          source venv/bin/activate
          pytest
