name: CI/CD Documentation Deployment

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v3

      - name: Installer Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Installer les dépendances
        run: |
          pip install pdoc pytest

      - name: Exécuter les tests
        run: |
          pytest

      - name: Générer la documentation
        run: |
          pdoc main.py -o docs

      - name: Déployer sur GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: docs
